### PR TITLE
Freeze downstreams in FakeNoteRepository

### PR DESCRIPTION
**Pull request by arkivanov**
This is required for proper testing. Real repository uses `observeOn` and freezes downstreams. Fake repository should do the same.

### CODE REVIEW

**Comment by saket** [comment]
Hey @arkivanov, given that the tests are already passing, is this actually needed? Or am I missing something and should the tests be updated to catch this?

**Comment by arkivanov** [comment]
Well, it is possible to brake the code and tests will pass) this PR ensures tests will fail

**Comment by arkivanov** [comment]
I can provide more details later

**Comment by saket** [comment]
Sure, whenever you get time. Also, congrats for adding macOS support to Reaktive 🎉!

**Comment by arkivanov** [comment]
Alright, the following patch will not work on production, however it will pass iOS tests on the current master. And it will fail iOS tests on this branch.
```
Index: shared/src/commonMain/kotlin/me/saket/press/shared/editor/EditorPresenter.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- shared/src/commonMain/kotlin/me/saket/press/shared/editor/EditorPresenter.kt	(revision b1ae5bedf4dd5c8d6cd9ba0732025f5bb9067da4)
+++ shared/src/commonMain/kotlin/me/saket/press/shared/editor/EditorPresenter.kt	(date 1577841456840)
@@ -143,7 +143,6 @@
 
   fun saveEditorContentOnExit(content: CharSequence) {
     updateOrDeleteNote(content.toString())
-        .subscribeOn(ioScheduler)
         .subscribe()
   }
 
@@ -156,6 +155,8 @@
       is ExistingNote -> openMode.noteUuid
     }
 
+    var n: Note? = null
+
     // For reasons I don't understand, noteStream doesn't get re-subscribed
     // when this function is called after EditorView gets detached. Fetching
     // the note again here.
@@ -163,6 +164,7 @@
         .take(1)
         .mapToSome()
         .flatMapCompletable { note ->
+          n = note
           when {
             shouldDelete -> noteRepository.markAsDeleted(note.uuid)
             else -> noteRepository.update(note.uuid, content)
```

**Comment by arkivanov** [comment]
Btw I do see some

**Comment by arkivanov** [comment]
Closed by accident, sorry. Reopened.

**Comment by arkivanov** [comment]
@saket Could you please either merge the PR or close if you are not interested in the improvement?

**Comment by saket** [comment]
Done. Thanks for sending this change!

**Pull request merged**
